### PR TITLE
[DEMO-2502] Convert to using requirements files

### PR DESCRIPTION
**Pull request by nr-kkenney**
* Instead of individually installing modules in the Dockerfile, use
a requirments file for python and ansible to collect the dependencies.
Then in the Dockerfile, install them using -r option.
* This simplifies using the tool locally since all ansible & python
dependencies can be installed in one command, and a dev no longer needs
to hunt down specific dependencies in the Dockerfile.

### CODE REVIEW

**Review by Julien4218 — COMMENTED** [review]
Hey @nr-kkenney 
While I like the improvement of installing dependencies from a requirement file, I'm not quite onboard with the way the partitioning has been done.
For example before, things that relates to AWS were grouped together to highlight what is needed for a given purpose. With the new layout, I'm no longer able to see at first glance that boto3 is required because AWS requires it.
Maybe @gabeobrien and @aswanson-nr might be interested chiming in too.

**Comment by aswanson-nr** [comment]
@Julien4218 That's a good point. I would also like to keep track of which dependencies are used for each purpose.
I would like to use this method for installing the dependencies, as it keeps them locked to one spot and makes setting up a dev environment easier. Why don't we add comments to the two files to denote what the dependencies are used for?

**Comment by gabeobrien** [comment]
I like the latest changes here.  Maybe @Julien4218 can take a look and see if this resolves his issues.

**Review by Julien4218 — APPROVED** [review]

**Comment by Julien4218** [comment]
It's ok now.
Side note, try using the lowest number for versioning, we don't always have to bump the minor number. In this instance, we haven't added any functionality, so I would have just incremented the last number (build/patch).

**Pull request merged**
