### PR TITLE
Fix/batch detect failure2

### PR DESCRIPTION
**Pull request by Julien4218**
## Summary

Fix failure detection when using batch mode

## Checklist
- [X ] Deployer version updated

### CODE REVIEW

**Comment by Julien4218** [comment]
@aswanson-nr @nr-kkenney this is the final piece to fix the batch mode, it wasn't detecting failure correctly before.
I've tested local and can see all the failure output at the end of the execution now.
Please approve and merge when time permits.

**Comment by aswanson-nr** [comment]
Hey @Julien4218, I'm seeing some related unit test failures, can you take a look at them when you have a moment?

**Comment by Julien4218** [comment]
> Hey @Julien4218, I'm seeing some related unit test failures, can you take a look at them when you have a moment?

Yes sorry @aswanson-nr , I was just in the middle of fixing those, I think they're good now.

**Review by aswanson-nr — APPROVED** [review]
Azure UAT failures do not appear to be related to the changes in this PR. Looks good to me

**Pull request merged**
